CREATE TABLE "orders" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"items" jsonb NOT NULL,
	"total" integer NOT NULL,
	"status" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbox_dead_letters" (
	"id" text PRIMARY KEY,
	"seq" bigint NOT NULL,
	"topic" text NOT NULL,
	"payload" jsonb,
	"headers" jsonb NOT NULL,
	"key" text,
	"created_at" timestamp with time zone NOT NULL,
	"attempts" integer NOT NULL,
	"last_error" text,
	"history" jsonb NOT NULL,
	"reason" text NOT NULL,
	"failed_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbox_inbox" (
	"consumer" text,
	"message_id" text,
	"processed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "outbox_inbox_pkey" PRIMARY KEY("consumer","message_id")
);
--> statement-breakpoint
CREATE TABLE "outbox_messages" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "outbox_messages_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text NOT NULL UNIQUE,
	"topic" text NOT NULL,
	"payload" jsonb,
	"headers" jsonb NOT NULL,
	"key" text,
	"created_at" timestamp with time zone NOT NULL,
	"available_at" timestamp with time zone NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"history" jsonb DEFAULT '[]' NOT NULL,
	"lease_owner" text,
	"lease_until" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"price" integer NOT NULL,
	"in_stock" integer NOT NULL,
	"reserved" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE INDEX "outbox_dead_letters_topic_failed_at" ON "outbox_dead_letters" ("topic","failed_at");--> statement-breakpoint
CREATE INDEX "outbox_inbox_processed_at" ON "outbox_inbox" ("processed_at");--> statement-breakpoint
CREATE INDEX "outbox_messages_key_seq" ON "outbox_messages" ("key","seq");